INSERT INTO adjectives (segment) VALUES ('24/7');
INSERT INTO adjectives (segment) VALUES ('accentuated');
INSERT INTO adjectives (segment) VALUES ('actual');
INSERT INTO adjectives (segment) VALUES ('acute');
INSERT INTO adjectives (segment) VALUES ('adjusted');
INSERT INTO adjectives (segment) VALUES ('all-around');
INSERT INTO adjectives (segment) VALUES ('always-on');
INSERT INTO adjectives (segment) VALUES ('anticipatory');
INSERT INTO adjectives (segment) VALUES ('astonishing');
INSERT INTO adjectives (segment) VALUES ('award-winning');
INSERT INTO adjectives (segment) VALUES ('B2B');
INSERT INTO adjectives (segment) VALUES ('back-end');
INSERT INTO adjectives (segment) VALUES ('back-office');
INSERT INTO adjectives (segment) VALUES ('best-of-breed');
INSERT INTO adjectives (segment) VALUES ('best-practices');
INSERT INTO adjectives (segment) VALUES ('better');
INSERT INTO adjectives (segment) VALUES ('bona fide');
INSERT INTO adjectives (segment) VALUES ('branded');
INSERT INTO adjectives (segment) VALUES ('branded');
INSERT INTO adjectives (segment) VALUES ('break-neck');
INSERT INTO adjectives (segment) VALUES ('cafeteria-style');
INSERT INTO adjectives (segment) VALUES ('central');
INSERT INTO adjectives (segment) VALUES ('cerebral');
INSERT INTO adjectives (segment) VALUES ('cherished');
INSERT INTO adjectives (segment) VALUES ('clickable');
INSERT INTO adjectives (segment) VALUES ('click-oriented');
INSERT INTO adjectives (segment) VALUES ('client');
INSERT INTO adjectives (segment) VALUES ('client/server');
INSERT INTO adjectives (segment) VALUES ('climactic');
INSERT INTO adjectives (segment) VALUES ('close');
INSERT INTO adjectives (segment) VALUES ('closed-door');
INSERT INTO adjectives (segment) VALUES ('co-branded');
INSERT INTO adjectives (segment) VALUES ('collateral');
INSERT INTO adjectives (segment) VALUES ('collective');
INSERT INTO adjectives (segment) VALUES ('committed');
INSERT INTO adjectives (segment) VALUES ('compiled');
INSERT INTO adjectives (segment) VALUES ('confidential');
INSERT INTO adjectives (segment) VALUES ('cool');
INSERT INTO adjectives (segment) VALUES ('cooperative');
INSERT INTO adjectives (segment) VALUES ('core');
INSERT INTO adjectives (segment) VALUES ('cross-industry');
INSERT INTO adjectives (segment) VALUES ('cross-media');
INSERT INTO adjectives (segment) VALUES ('cross-organization');
INSERT INTO adjectives (segment) VALUES ('cross-platform');
INSERT INTO adjectives (segment) VALUES ('crucial');
INSERT INTO adjectives (segment) VALUES ('custom');
INSERT INTO adjectives (segment) VALUES ('customer-driven');
INSERT INTO adjectives (segment) VALUES ('customized');
INSERT INTO adjectives (segment) VALUES ('cutting-edge');
INSERT INTO adjectives (segment) VALUES ('defacto');
INSERT INTO adjectives (segment) VALUES ('dependent');
INSERT INTO adjectives (segment) VALUES ('digital');
INSERT INTO adjectives (segment) VALUES ('distributed');
INSERT INTO adjectives (segment) VALUES ('diversified');
INSERT INTO adjectives (segment) VALUES ('dot-com');
INSERT INTO adjectives (segment) VALUES ('downside');
INSERT INTO adjectives (segment) VALUES ('drilled-down');
INSERT INTO adjectives (segment) VALUES ('dynamic');
INSERT INTO adjectives (segment) VALUES ('Earth-friendly');
INSERT INTO adjectives (segment) VALUES ('e-business');
INSERT INTO adjectives (segment) VALUES ('efficient');
INSERT INTO adjectives (segment) VALUES ('emergent');
INSERT INTO adjectives (segment) VALUES ('emerging');
INSERT INTO adjectives (segment) VALUES ('end-to-end');
INSERT INTO adjectives (segment) VALUES ('enterprise');
INSERT INTO adjectives (segment) VALUES ('e-tail');
INSERT INTO adjectives (segment) VALUES ('evangelic');
INSERT INTO adjectives (segment) VALUES ('evangelistic');
INSERT INTO adjectives (segment) VALUES ('evident');
INSERT INTO adjectives (segment) VALUES ('extensible');
INSERT INTO adjectives (segment) VALUES ('extreme');
INSERT INTO adjectives (segment) VALUES ('facilitated');
INSERT INTO adjectives (segment) VALUES ('first class');
INSERT INTO adjectives (segment) VALUES ('first-to-market');
INSERT INTO adjectives (segment) VALUES ('focused');
INSERT INTO adjectives (segment) VALUES ('formatted');
INSERT INTO adjectives (segment) VALUES ('front-end');
INSERT INTO adjectives (segment) VALUES ('fully qualified');
INSERT INTO adjectives (segment) VALUES ('fusioned');
INSERT INTO adjectives (segment) VALUES ('futuristic');
INSERT INTO adjectives (segment) VALUES ('gamified');
INSERT INTO adjectives (segment) VALUES ('global');
INSERT INTO adjectives (segment) VALUES ('granular');
INSERT INTO adjectives (segment) VALUES ('green');
INSERT INTO adjectives (segment) VALUES ('ground-breaking');
INSERT INTO adjectives (segment) VALUES ('ground-zero');
INSERT INTO adjectives (segment) VALUES ('high-speed');
INSERT INTO adjectives (segment) VALUES ('high-speed');
INSERT INTO adjectives (segment) VALUES ('impactful');
INSERT INTO adjectives (segment) VALUES ('incremental');
INSERT INTO adjectives (segment) VALUES ('infiltrating');
INSERT INTO adjectives (segment) VALUES ('innovative');
INSERT INTO adjectives (segment) VALUES ('insightful');
INSERT INTO adjectives (segment) VALUES ('integrated');
INSERT INTO adjectives (segment) VALUES ('intellectual');
INSERT INTO adjectives (segment) VALUES ('intelligent');
INSERT INTO adjectives (segment) VALUES ('interactive');
INSERT INTO adjectives (segment) VALUES ('intuitive');
INSERT INTO adjectives (segment) VALUES ('invaluable');
INSERT INTO adjectives (segment) VALUES ('just-in-time');
INSERT INTO adjectives (segment) VALUES ('keen');
INSERT INTO adjectives (segment) VALUES ('leading-edge');
INSERT INTO adjectives (segment) VALUES ('mapped');
INSERT INTO adjectives (segment) VALUES ('market-driven');
INSERT INTO adjectives (segment) VALUES ('market-sensitive');
INSERT INTO adjectives (segment) VALUES ('material');
INSERT INTO adjectives (segment) VALUES ('matrixed');
INSERT INTO adjectives (segment) VALUES ('meshed');
INSERT INTO adjectives (segment) VALUES ('mission-critical');
INSERT INTO adjectives (segment) VALUES ('mixed');
INSERT INTO adjectives (segment) VALUES ('mobile');
INSERT INTO adjectives (segment) VALUES ('motivated');
INSERT INTO adjectives (segment) VALUES ('motivational');
INSERT INTO adjectives (segment) VALUES ('networkable');
INSERT INTO adjectives (segment) VALUES ('new and unusual');
INSERT INTO adjectives (segment) VALUES ('new-fashioned');
INSERT INTO adjectives (segment) VALUES ('next-day');
INSERT INTO adjectives (segment) VALUES ('next-generation');
INSERT INTO adjectives (segment) VALUES ('omnipotent');
INSERT INTO adjectives (segment) VALUES ('one-to-one');
INSERT INTO adjectives (segment) VALUES ('on-the-go');
INSERT INTO adjectives (segment) VALUES ('open architecture');
INSERT INTO adjectives (segment) VALUES ('open-door');
INSERT INTO adjectives (segment) VALUES ('open-source');
INSERT INTO adjectives (segment) VALUES ('out-of-the-box');
INSERT INTO adjectives (segment) VALUES ('outside-in');
INSERT INTO adjectives (segment) VALUES ('outsourced');
INSERT INTO adjectives (segment) VALUES ('over-engineered');
INSERT INTO adjectives (segment) VALUES ('over-under');
INSERT INTO adjectives (segment) VALUES ('paradisiacal');
INSERT INTO adjectives (segment) VALUES ('partial');
INSERT INTO adjectives (segment) VALUES ('patterned');
INSERT INTO adjectives (segment) VALUES ('pending');
INSERT INTO adjectives (segment) VALUES ('penetrating');
INSERT INTO adjectives (segment) VALUES ('pilot');
INSERT INTO adjectives (segment) VALUES ('pipelined');
INSERT INTO adjectives (segment) VALUES ('plug-and-play');
INSERT INTO adjectives (segment) VALUES ('pointed');
INSERT INTO adjectives (segment) VALUES ('politically correct');
INSERT INTO adjectives (segment) VALUES ('portable');
INSERT INTO adjectives (segment) VALUES ('positioned');
INSERT INTO adjectives (segment) VALUES ('positive');
INSERT INTO adjectives (segment) VALUES ('potential vs. actual');
INSERT INTO adjectives (segment) VALUES ('precognizant');
INSERT INTO adjectives (segment) VALUES ('prescient');
INSERT INTO adjectives (segment) VALUES ('priceless');
INSERT INTO adjectives (segment) VALUES ('proactive (not reactive)');
INSERT INTO adjectives (segment) VALUES ('proactive');
INSERT INTO adjectives (segment) VALUES ('progressive');
INSERT INTO adjectives (segment) VALUES ('proprietary');
INSERT INTO adjectives (segment) VALUES ('proprietary');
INSERT INTO adjectives (segment) VALUES ('qualified');
INSERT INTO adjectives (segment) VALUES ('rapid-fire');
INSERT INTO adjectives (segment) VALUES ('rave');
INSERT INTO adjectives (segment) VALUES ('raw');
INSERT INTO adjectives (segment) VALUES ('reactive');
INSERT INTO adjectives (segment) VALUES ('real-time');
INSERT INTO adjectives (segment) VALUES ('red-lined');
INSERT INTO adjectives (segment) VALUES ('relational');
INSERT INTO adjectives (segment) VALUES ('renowned');
INSERT INTO adjectives (segment) VALUES ('revenuable');
INSERT INTO adjectives (segment) VALUES ('revolutionary');
INSERT INTO adjectives (segment) VALUES ('robust');
INSERT INTO adjectives (segment) VALUES ('same-day');
INSERT INTO adjectives (segment) VALUES ('scalable');
INSERT INTO adjectives (segment) VALUES ('seamless');
INSERT INTO adjectives (segment) VALUES ('secret');
INSERT INTO adjectives (segment) VALUES ('seven-habits-conforming');
INSERT INTO adjectives (segment) VALUES ('smoking');
INSERT INTO adjectives (segment) VALUES ('solutioned');
INSERT INTO adjectives (segment) VALUES ('spiritualistic');
INSERT INTO adjectives (segment) VALUES ('spontaneous');
INSERT INTO adjectives (segment) VALUES ('state-of-the-art');
INSERT INTO adjectives (segment) VALUES ('sticky');
INSERT INTO adjectives (segment) VALUES ('strategic');
INSERT INTO adjectives (segment) VALUES ('stratified');
INSERT INTO adjectives (segment) VALUES ('structured');
INSERT INTO adjectives (segment) VALUES ('subordinate');
INSERT INTO adjectives (segment) VALUES ('surgically targeted');
INSERT INTO adjectives (segment) VALUES ('synergistic');
INSERT INTO adjectives (segment) VALUES ('take-no-prisoners');
INSERT INTO adjectives (segment) VALUES ('thin');
INSERT INTO adjectives (segment) VALUES ('thoroughbred');
INSERT INTO adjectives (segment) VALUES ('three-pronged');
INSERT INTO adjectives (segment) VALUES ('thumbnailed');
INSERT INTO adjectives (segment) VALUES ('tiered');
INSERT INTO adjectives (segment) VALUES ('top-down');
INSERT INTO adjectives (segment) VALUES ('top-heavy');
INSERT INTO adjectives (segment) VALUES ('top-shelf');
INSERT INTO adjectives (segment) VALUES ('transparent');
INSERT INTO adjectives (segment) VALUES ('trend-setting');
INSERT INTO adjectives (segment) VALUES ('turn-key');
INSERT INTO adjectives (segment) VALUES ('ubiquitous');
INSERT INTO adjectives (segment) VALUES ('ultra-cool');
INSERT INTO adjectives (segment) VALUES ('unary');
INSERT INTO adjectives (segment) VALUES ('uncommon');
INSERT INTO adjectives (segment) VALUES ('unfamiliar');
INSERT INTO adjectives (segment) VALUES ('unified');
INSERT INTO adjectives (segment) VALUES ('unique');
INSERT INTO adjectives (segment) VALUES ('unmistakable');
INSERT INTO adjectives (segment) VALUES ('up-and-over');
INSERT INTO adjectives (segment) VALUES ('upside');
INSERT INTO adjectives (segment) VALUES ('user-centric');
INSERT INTO adjectives (segment) VALUES ('value-added');
INSERT INTO adjectives (segment) VALUES ('venerable');
INSERT INTO adjectives (segment) VALUES ('ventures in');
INSERT INTO adjectives (segment) VALUES ('verified');
INSERT INTO adjectives (segment) VALUES ('vertical');
INSERT INTO adjectives (segment) VALUES ('virtual');
INSERT INTO adjectives (segment) VALUES ('virtualized');
INSERT INTO adjectives (segment) VALUES ('visionary');
INSERT INTO adjectives (segment) VALUES ('wall-to-wall');
INSERT INTO adjectives (segment) VALUES ('web-enabled');
INSERT INTO adjectives (segment) VALUES ('wide-open');
INSERT INTO adjectives (segment) VALUES ('wireless');
INSERT INTO adjectives (segment) VALUES ('world-class');
INSERT INTO adjectives (segment) VALUES ('zero-deviation');


INSERT INTO connectors (segment) VALUES (' ');
INSERT INTO connectors (segment) VALUES (' ');
INSERT INTO connectors (segment) VALUES ('a few');
INSERT INTO connectors (segment) VALUES ('a leadership role in the');
INSERT INTO connectors (segment) VALUES ('ad hoc');
INSERT INTO connectors (segment) VALUES ('all');
INSERT INTO connectors (segment) VALUES ('all-encompassing');
INSERT INTO connectors (segment) VALUES ('connected');
INSERT INTO connectors (segment) VALUES ('definitive');
INSERT INTO connectors (segment) VALUES ('dimensional');
INSERT INTO connectors (segment) VALUES ('flagship');
INSERT INTO connectors (segment) VALUES ('industry-standard');
INSERT INTO connectors (segment) VALUES ('infinity-plus');
INSERT INTO connectors (segment) VALUES ('insourced');
INSERT INTO connectors (segment) VALUES ('invisible');
INSERT INTO connectors (segment) VALUES ('many');
INSERT INTO connectors (segment) VALUES ('median');
INSERT INTO connectors (segment) VALUES ('more');
INSERT INTO connectors (segment) VALUES ('multiple');
INSERT INTO connectors (segment) VALUES ('multiple');
INSERT INTO connectors (segment) VALUES ('only the best');
INSERT INTO connectors (segment) VALUES ('opaque');
INSERT INTO connectors (segment) VALUES ('our');
INSERT INTO connectors (segment) VALUES ('our client''s');
INSERT INTO connectors (segment) VALUES ('plugged-in');
INSERT INTO connectors (segment) VALUES ('shifted');
INSERT INTO connectors (segment) VALUES ('some');
INSERT INTO connectors (segment) VALUES ('some face time with the');
INSERT INTO connectors (segment) VALUES ('strategic');
INSERT INTO connectors (segment) VALUES ('tactical');
INSERT INTO connectors (segment) VALUES ('the');
INSERT INTO connectors (segment) VALUES ('the best');
INSERT INTO connectors (segment) VALUES ('the company''s');
INSERT INTO connectors (segment) VALUES ('the competition''s');
INSERT INTO connectors (segment) VALUES ('the customer''s');
INSERT INTO connectors (segment) VALUES ('the matrix of');
INSERT INTO connectors (segment) VALUES ('the most');
INSERT INTO connectors (segment) VALUES ('tomorrow''s');
INSERT INTO connectors (segment) VALUES ('unplugged');
INSERT INTO connectors (segment) VALUES ('virtual');
INSERT INTO connectors (segment) VALUES ('visible');
INSERT INTO connectors (segment) VALUES ('warehouses full of');
INSERT INTO connectors (segment) VALUES ('your');


INSERT INTO nouns (segment) VALUES ('action-items');
INSERT INTO nouns (segment) VALUES ('affairs');
INSERT INTO nouns (segment) VALUES ('affinities');
INSERT INTO nouns (segment) VALUES ('algorithms of strategy');
INSERT INTO nouns (segment) VALUES ('analogues');
INSERT INTO nouns (segment) VALUES ('applications');
INSERT INTO nouns (segment) VALUES ('aptitudes');
INSERT INTO nouns (segment) VALUES ('architectures');
INSERT INTO nouns (segment) VALUES ('areas of influence');
INSERT INTO nouns (segment) VALUES ('areas');
INSERT INTO nouns (segment) VALUES ('arrays of clients');
INSERT INTO nouns (segment) VALUES ('assumptions');
INSERT INTO nouns (segment) VALUES ('attainments');
INSERT INTO nouns (segment) VALUES ('bandwidths');
INSERT INTO nouns (segment) VALUES ('baselines');
INSERT INTO nouns (segment) VALUES ('bases');
INSERT INTO nouns (segment) VALUES ('beginnings');
INSERT INTO nouns (segment) VALUES ('bells and whistles');
INSERT INTO nouns (segment) VALUES ('benefits');
INSERT INTO nouns (segment) VALUES ('birthings');
INSERT INTO nouns (segment) VALUES ('blips on the radar screen');
INSERT INTO nouns (segment) VALUES ('body counts');
INSERT INTO nouns (segment) VALUES ('body languages');
INSERT INTO nouns (segment) VALUES ('bonuses');
INSERT INTO nouns (segment) VALUES ('boot camps');
INSERT INTO nouns (segment) VALUES ('bottom lines');
INSERT INTO nouns (segment) VALUES ('brain dumps');
INSERT INTO nouns (segment) VALUES ('brand awareness');
INSERT INTO nouns (segment) VALUES ('brand recognition');
INSERT INTO nouns (segment) VALUES ('brands');
INSERT INTO nouns (segment) VALUES ('buckets');
INSERT INTO nouns (segment) VALUES ('budgets');
INSERT INTO nouns (segment) VALUES ('buying signs');
INSERT INTO nouns (segment) VALUES ('buzzes');
INSERT INTO nouns (segment) VALUES ('channel partners');
INSERT INTO nouns (segment) VALUES ('channels');
INSERT INTO nouns (segment) VALUES ('characteristics');
INSERT INTO nouns (segment) VALUES ('circles of influence');
INSERT INTO nouns (segment) VALUES ('click cliques');
INSERT INTO nouns (segment) VALUES ('click-sploitations');
INSERT INTO nouns (segment) VALUES ('client competencies');
INSERT INTO nouns (segment) VALUES ('client criticalities');
INSERT INTO nouns (segment) VALUES ('client engagements');
INSERT INTO nouns (segment) VALUES ('client preferences');
INSERT INTO nouns (segment) VALUES ('client sensibilities');
INSERT INTO nouns (segment) VALUES ('client-vendor alloys');
INSERT INTO nouns (segment) VALUES ('clock cycles');
INSERT INTO nouns (segment) VALUES ('closing ratios');
INSERT INTO nouns (segment) VALUES ('coalitions');
INSERT INTO nouns (segment) VALUES ('comfort zones');
INSERT INTO nouns (segment) VALUES ('commission opportunities');
INSERT INTO nouns (segment) VALUES ('committees');
INSERT INTO nouns (segment) VALUES ('communities');
INSERT INTO nouns (segment) VALUES ('company jewels');
INSERT INTO nouns (segment) VALUES ('competencies');
INSERT INTO nouns (segment) VALUES ('competency streams');
INSERT INTO nouns (segment) VALUES ('compilations');
INSERT INTO nouns (segment) VALUES ('conclusions');
INSERT INTO nouns (segment) VALUES ('conference calls');
INSERT INTO nouns (segment) VALUES ('conjectures');
INSERT INTO nouns (segment) VALUES ('constants');
INSERT INTO nouns (segment) VALUES ('content');
INSERT INTO nouns (segment) VALUES ('contents');
INSERT INTO nouns (segment) VALUES ('contexts');
INSERT INTO nouns (segment) VALUES ('convergences');
INSERT INTO nouns (segment) VALUES ('co-opetition');
INSERT INTO nouns (segment) VALUES ('cost centers');
INSERT INTO nouns (segment) VALUES ('costs of success');
INSERT INTO nouns (segment) VALUES ('costs');
INSERT INTO nouns (segment) VALUES ('courses of action');
INSERT INTO nouns (segment) VALUES ('CPU cycles');
INSERT INTO nouns (segment) VALUES ('criteria');
INSERT INTO nouns (segment) VALUES ('customer engagements');
INSERT INTO nouns (segment) VALUES ('customer glidepaths');
INSERT INTO nouns (segment) VALUES ('data mines');
INSERT INTO nouns (segment) VALUES ('data mining');
INSERT INTO nouns (segment) VALUES ('data points');
INSERT INTO nouns (segment) VALUES ('data translucencies');
INSERT INTO nouns (segment) VALUES ('definitions');
INSERT INTO nouns (segment) VALUES ('deliverables');
INSERT INTO nouns (segment) VALUES ('deltas');
INSERT INTO nouns (segment) VALUES ('demands');
INSERT INTO nouns (segment) VALUES ('destinations');
INSERT INTO nouns (segment) VALUES ('disciplines');
INSERT INTO nouns (segment) VALUES ('distribution channels');
INSERT INTO nouns (segment) VALUES ('distribution powerhouses');
INSERT INTO nouns (segment) VALUES ('dividing lines');
INSERT INTO nouns (segment) VALUES ('dog and pony shows');
INSERT INTO nouns (segment) VALUES ('e-commerce');
INSERT INTO nouns (segment) VALUES ('e-customers');
INSERT INTO nouns (segment) VALUES ('effects of synergy');
INSERT INTO nouns (segment) VALUES ('efforts');
INSERT INTO nouns (segment) VALUES ('e-handshakes');
INSERT INTO nouns (segment) VALUES ('e-markets');
INSERT INTO nouns (segment) VALUES ('empowerments');
INSERT INTO nouns (segment) VALUES ('enablements');
INSERT INTO nouns (segment) VALUES ('entireties');
INSERT INTO nouns (segment) VALUES ('enumerations');
INSERT INTO nouns (segment) VALUES ('e-revenues');
INSERT INTO nouns (segment) VALUES ('e-services');
INSERT INTO nouns (segment) VALUES ('eventualities');
INSERT INTO nouns (segment) VALUES ('examples');
INSERT INTO nouns (segment) VALUES ('executions');
INSERT INTO nouns (segment) VALUES ('executive compensation plans');
INSERT INTO nouns (segment) VALUES ('expediencies');
INSERT INTO nouns (segment) VALUES ('externalizations');
INSERT INTO nouns (segment) VALUES ('extranets');
INSERT INTO nouns (segment) VALUES ('fabrics of synergy');
INSERT INTO nouns (segment) VALUES ('fax blasts');
INSERT INTO nouns (segment) VALUES ('feature sets');
INSERT INTO nouns (segment) VALUES ('features');
INSERT INTO nouns (segment) VALUES ('fertile grounds');
INSERT INTO nouns (segment) VALUES ('finish lines');
INSERT INTO nouns (segment) VALUES ('flashes in the pan');
INSERT INTO nouns (segment) VALUES ('flood gates');
INSERT INTO nouns (segment) VALUES ('focus groups');
INSERT INTO nouns (segment) VALUES ('focuses');
INSERT INTO nouns (segment) VALUES ('formalizations');
INSERT INTO nouns (segment) VALUES ('fulfillments');
INSERT INTO nouns (segment) VALUES ('functionalities');
INSERT INTO nouns (segment) VALUES ('fusions');
INSERT INTO nouns (segment) VALUES ('futilities');
INSERT INTO nouns (segment) VALUES ('game plans');
INSERT INTO nouns (segment) VALUES ('goal posts');
INSERT INTO nouns (segment) VALUES ('golden parachutes');
INSERT INTO nouns (segment) VALUES ('''gotta haves''');
INSERT INTO nouns (segment) VALUES ('gravy trains');
INSERT INTO nouns (segment) VALUES ('group synergies');
INSERT INTO nouns (segment) VALUES ('hot buttons');
INSERT INTO nouns (segment) VALUES ('icing on the cakes');
INSERT INTO nouns (segment) VALUES ('ideals');
INSERT INTO nouns (segment) VALUES ('impacts');
INSERT INTO nouns (segment) VALUES ('implementations');
INSERT INTO nouns (segment) VALUES ('impressions');
INSERT INTO nouns (segment) VALUES ('incomes');
INSERT INTO nouns (segment) VALUES ('incubations');
INSERT INTO nouns (segment) VALUES ('incubators');
INSERT INTO nouns (segment) VALUES ('industry road maps');
INSERT INTO nouns (segment) VALUES ('inflows');
INSERT INTO nouns (segment) VALUES ('information');
INSERT INTO nouns (segment) VALUES ('infrastructures');
INSERT INTO nouns (segment) VALUES ('initiatives');
INSERT INTO nouns (segment) VALUES ('inputs');
INSERT INTO nouns (segment) VALUES ('integrities');
INSERT INTO nouns (segment) VALUES ('interconnections');
INSERT INTO nouns (segment) VALUES ('interfaces');
INSERT INTO nouns (segment) VALUES ('Internet appliances');
INSERT INTO nouns (segment) VALUES ('Intranets');
INSERT INTO nouns (segment) VALUES ('knowledge streams');
INSERT INTO nouns (segment) VALUES ('laser-like focuses on the bottom line');
INSERT INTO nouns (segment) VALUES ('launches');
INSERT INTO nouns (segment) VALUES ('laundry lists');
INSERT INTO nouns (segment) VALUES ('layers of management');
INSERT INTO nouns (segment) VALUES ('layouts');
INSERT INTO nouns (segment) VALUES ('leveraged synergies');
INSERT INTO nouns (segment) VALUES ('leverages');
INSERT INTO nouns (segment) VALUES ('line items');
INSERT INTO nouns (segment) VALUES ('litmus tests');
INSERT INTO nouns (segment) VALUES ('living documents');
INSERT INTO nouns (segment) VALUES ('management layers');
INSERT INTO nouns (segment) VALUES ('managerial voids');
INSERT INTO nouns (segment) VALUES ('margin deltas');
INSERT INTO nouns (segment) VALUES ('margin spreads');
INSERT INTO nouns (segment) VALUES ('margins');
INSERT INTO nouns (segment) VALUES ('market trends');
INSERT INTO nouns (segment) VALUES ('market voids');
INSERT INTO nouns (segment) VALUES ('markets');
INSERT INTO nouns (segment) VALUES ('MBOs');
INSERT INTO nouns (segment) VALUES ('measurements');
INSERT INTO nouns (segment) VALUES ('meetings');
INSERT INTO nouns (segment) VALUES ('metrics');
INSERT INTO nouns (segment) VALUES ('mind gems');
INSERT INTO nouns (segment) VALUES ('mindshares');
INSERT INTO nouns (segment) VALUES ('missions');
INSERT INTO nouns (segment) VALUES ('models');
INSERT INTO nouns (segment) VALUES ('movers and shakers');
INSERT INTO nouns (segment) VALUES ('multiplicities');
INSERT INTO nouns (segment) VALUES ('net-nets');
INSERT INTO nouns (segment) VALUES ('networks');
INSERT INTO nouns (segment) VALUES ('niches');
INSERT INTO nouns (segment) VALUES ('notions');
INSERT INTO nouns (segment) VALUES ('objections');
INSERT INTO nouns (segment) VALUES ('objectives');
INSERT INTO nouns (segment) VALUES ('opportunities');
INSERT INTO nouns (segment) VALUES ('organizations');
INSERT INTO nouns (segment) VALUES ('ouch factors');
INSERT INTO nouns (segment) VALUES ('outcomes');
INSERT INTO nouns (segment) VALUES ('overviews');
INSERT INTO nouns (segment) VALUES ('P&L sheets');
INSERT INTO nouns (segment) VALUES ('panic factors');
INSERT INTO nouns (segment) VALUES ('paradigm shifts');
INSERT INTO nouns (segment) VALUES ('paradigms');
INSERT INTO nouns (segment) VALUES ('parameters');
INSERT INTO nouns (segment) VALUES ('partner pairings');
INSERT INTO nouns (segment) VALUES ('partnerships');
INSERT INTO nouns (segment) VALUES ('paths');
INSERT INTO nouns (segment) VALUES ('patterns of change');
INSERT INTO nouns (segment) VALUES ('patterns');
INSERT INTO nouns (segment) VALUES ('penetrations');
INSERT INTO nouns (segment) VALUES ('pep rallies');
INSERT INTO nouns (segment) VALUES ('pipelines');
INSERT INTO nouns (segment) VALUES ('pixel densities');
INSERT INTO nouns (segment) VALUES ('platforms');
INSERT INTO nouns (segment) VALUES ('portals');
INSERT INTO nouns (segment) VALUES ('positionings');
INSERT INTO nouns (segment) VALUES ('positions');
INSERT INTO nouns (segment) VALUES ('preferences');
INSERT INTO nouns (segment) VALUES ('presentations');
INSERT INTO nouns (segment) VALUES ('principles');
INSERT INTO nouns (segment) VALUES ('probes');
INSERT INTO nouns (segment) VALUES ('product amalgams');
INSERT INTO nouns (segment) VALUES ('productivities');
INSERT INTO nouns (segment) VALUES ('profiles');
INSERT INTO nouns (segment) VALUES ('proposals');
INSERT INTO nouns (segment) VALUES ('punch lists');
INSERT INTO nouns (segment) VALUES ('purposes');
INSERT INTO nouns (segment) VALUES ('quality circles');
INSERT INTO nouns (segment) VALUES ('reality checks');
INSERT INTO nouns (segment) VALUES ('reality improvements');
INSERT INTO nouns (segment) VALUES ('recompenses');
INSERT INTO nouns (segment) VALUES ('red flags');
INSERT INTO nouns (segment) VALUES ('references');
INSERT INTO nouns (segment) VALUES ('relationships');
INSERT INTO nouns (segment) VALUES ('relevances');
INSERT INTO nouns (segment) VALUES ('remunerations');
INSERT INTO nouns (segment) VALUES ('reorganizations');
INSERT INTO nouns (segment) VALUES ('reorgs');
INSERT INTO nouns (segment) VALUES ('reportables');
INSERT INTO nouns (segment) VALUES ('resolutions');
INSERT INTO nouns (segment) VALUES ('resource inventories');
INSERT INTO nouns (segment) VALUES ('resources');
INSERT INTO nouns (segment) VALUES ('responsibilities');
INSERT INTO nouns (segment) VALUES ('revenewals');
INSERT INTO nouns (segment) VALUES ('revenue densities');
INSERT INTO nouns (segment) VALUES ('revenue injections');
INSERT INTO nouns (segment) VALUES ('revenue points');
INSERT INTO nouns (segment) VALUES ('revenues');
INSERT INTO nouns (segment) VALUES ('RFPs');
INSERT INTO nouns (segment) VALUES ('ROIs');
INSERT INTO nouns (segment) VALUES ('safety valves');
INSERT INTO nouns (segment) VALUES ('scatter factors');
INSERT INTO nouns (segment) VALUES ('schemas');
INSERT INTO nouns (segment) VALUES ('sensibilities');
INSERT INTO nouns (segment) VALUES ('shots in the arm');
INSERT INTO nouns (segment) VALUES ('shots in the dark');
INSERT INTO nouns (segment) VALUES ('show-stoppers');
INSERT INTO nouns (segment) VALUES ('signals');
INSERT INTO nouns (segment) VALUES ('significations');
INSERT INTO nouns (segment) VALUES ('silver bullets');
INSERT INTO nouns (segment) VALUES ('skill sets');
INSERT INTO nouns (segment) VALUES ('slide shows');
INSERT INTO nouns (segment) VALUES ('smoke and mirrors presentations');
INSERT INTO nouns (segment) VALUES ('solutions');
INSERT INTO nouns (segment) VALUES ('space');
INSERT INTO nouns (segment) VALUES ('spaces');
INSERT INTO nouns (segment) VALUES ('spheres of influence');
INSERT INTO nouns (segment) VALUES ('spin factors');
INSERT INTO nouns (segment) VALUES ('standards');
INSERT INTO nouns (segment) VALUES ('standards');
INSERT INTO nouns (segment) VALUES ('stock options');
INSERT INTO nouns (segment) VALUES ('stock prices');
INSERT INTO nouns (segment) VALUES ('stock trends');
INSERT INTO nouns (segment) VALUES ('strategies');
INSERT INTO nouns (segment) VALUES ('success positionings');
INSERT INTO nouns (segment) VALUES ('success stories');
INSERT INTO nouns (segment) VALUES ('sum totals');
INSERT INTO nouns (segment) VALUES ('supply lines');
INSERT INTO nouns (segment) VALUES ('synergies');
INSERT INTO nouns (segment) VALUES ('synergizations');
INSERT INTO nouns (segment) VALUES ('synergy factors');
INSERT INTO nouns (segment) VALUES ('systems');
INSERT INTO nouns (segment) VALUES ('tactical approaches');
INSERT INTO nouns (segment) VALUES ('tactics');
INSERT INTO nouns (segment) VALUES ('tactics');
INSERT INTO nouns (segment) VALUES ('targets');
INSERT INTO nouns (segment) VALUES ('team-building experiences');
INSERT INTO nouns (segment) VALUES ('teams');
INSERT INTO nouns (segment) VALUES ('technical playgrounds');
INSERT INTO nouns (segment) VALUES ('technologies');
INSERT INTO nouns (segment) VALUES ('technology overdrafts');
INSERT INTO nouns (segment) VALUES ('templates');
INSERT INTO nouns (segment) VALUES ('tensile strengths');
INSERT INTO nouns (segment) VALUES ('test balloons');
INSERT INTO nouns (segment) VALUES ('tiers');
INSERT INTO nouns (segment) VALUES ('TLAs');
INSERT INTO nouns (segment) VALUES ('totals');
INSERT INTO nouns (segment) VALUES ('tractions');
INSERT INTO nouns (segment) VALUES ('transformations');
INSERT INTO nouns (segment) VALUES ('trend lines');
INSERT INTO nouns (segment) VALUES ('trends');
INSERT INTO nouns (segment) VALUES ('turning points');
INSERT INTO nouns (segment) VALUES ('universes');
INSERT INTO nouns (segment) VALUES ('upshots');
INSERT INTO nouns (segment) VALUES ('users');
INSERT INTO nouns (segment) VALUES ('values');
INSERT INTO nouns (segment) VALUES ('variables');
INSERT INTO nouns (segment) VALUES ('venture capitalists');
INSERT INTO nouns (segment) VALUES ('ventures');
INSERT INTO nouns (segment) VALUES ('victory dances');
INSERT INTO nouns (segment) VALUES ('views from 30,000 feet');
INSERT INTO nouns (segment) VALUES ('virtualizations');
INSERT INTO nouns (segment) VALUES ('visualizations');
INSERT INTO nouns (segment) VALUES ('vortals');
INSERT INTO nouns (segment) VALUES ('Vulcan mind-melds');
INSERT INTO nouns (segment) VALUES ('webenues');
INSERT INTO nouns (segment) VALUES ('webfronts');
INSERT INTO nouns (segment) VALUES ('webifications');
INSERT INTO nouns (segment) VALUES ('webinars');
INSERT INTO nouns (segment) VALUES ('webtricity');
INSERT INTO nouns (segment) VALUES ('wins');
INSERT INTO nouns (segment) VALUES ('win-win situations');
INSERT INTO nouns (segment) VALUES ('yardsticks');


INSERT INTO prefixes (segment) VALUES ('A few of you are going to');
INSERT INTO prefixes (segment) VALUES ('A good manager doesn''t need to know how to do his subordinate''s work.  Now, please');
INSERT INTO prefixes (segment) VALUES ('All future correspondence should refer to our initiative to');
INSERT INTO prefixes (segment) VALUES ('An attribute of a good manager is that he/she knows how to');
INSERT INTO prefixes (segment) VALUES ('An effective VP is one who will unilaterally');
INSERT INTO prefixes (segment) VALUES ('Any good manager knows how to');
INSERT INTO prefixes (segment) VALUES ('Anybody could do your job.  But only I can');
INSERT INTO prefixes (segment) VALUES ('Are you a team player? Then you need to');
INSERT INTO prefixes (segment) VALUES ('As a member of the synergy improvement committee, you need to');
INSERT INTO prefixes (segment) VALUES ('As a team, we shall');
INSERT INTO prefixes (segment) VALUES ('As an executive, it is my privilege and duty to');
INSERT INTO prefixes (segment) VALUES ('As they say in the CEO''s office, we must');
INSERT INTO prefixes (segment) VALUES ('Associates who criticize their manager are not team players.  They need to');
INSERT INTO prefixes (segment) VALUES ('Associates who practice good work habits take the time to');
INSERT INTO prefixes (segment) VALUES ('At your next client engagement, you should');
INSERT INTO prefixes (segment) VALUES ('Attend to the details, and let the Vice Presidents');
INSERT INTO prefixes (segment) VALUES ('Bathrooms in the workplace are an employee benefit.  I want you to');
INSERT INTO prefixes (segment) VALUES ('Being a CEO is not easy.  That''s why I');
INSERT INTO prefixes (segment) VALUES ('Clearly, you need to improve the way that you');
INSERT INTO prefixes (segment) VALUES ('Customers choose us over the competition because we');
INSERT INTO prefixes (segment) VALUES ('Demonstrate a can-do attitude. Just');
INSERT INTO prefixes (segment) VALUES ('Do as your manager does, and');
INSERT INTO prefixes (segment) VALUES ('Do one thing.  Do it right.  For example,');
INSERT INTO prefixes (segment) VALUES ('Don''t criticize your manager unless you');
INSERT INTO prefixes (segment) VALUES ('Don''t get bogged down in details.  Instead,');
INSERT INTO prefixes (segment) VALUES ('Don''t underestimate the value of associates who');
INSERT INTO prefixes (segment) VALUES ('Dynamically, you can');
INSERT INTO prefixes (segment) VALUES ('Effective immediately, all associates will');
INSERT INTO prefixes (segment) VALUES ('Effectively, you must');
INSERT INTO prefixes (segment) VALUES ('Embrace the paradigm and');
INSERT INTO prefixes (segment) VALUES ('Embrace the synergy!  Leverage the enablement! Envision the focus!  And, finally,');
INSERT INTO prefixes (segment) VALUES ('Evangelize solutions!  Enable paradigms!  Evolve synergy!  And');
INSERT INTO prefixes (segment) VALUES ('Follow my example.  I');
INSERT INTO prefixes (segment) VALUES ('For the customer''s sake, we must');
INSERT INTO prefixes (segment) VALUES ('Foster synergy by fulcruming our leverage, and be sure to');
INSERT INTO prefixes (segment) VALUES ('Help your manager solution paradigms. Just');
INSERT INTO prefixes (segment) VALUES ('I am adding additional quality circles so that we can');
INSERT INTO prefixes (segment) VALUES ('I am adding more vice presidents so that we can');
INSERT INTO prefixes (segment) VALUES ('I am creating breakout teams that will');
INSERT INTO prefixes (segment) VALUES ('I believe that it is essential that we');
INSERT INTO prefixes (segment) VALUES ('I have an MBA.  Therefore, I');
INSERT INTO prefixes (segment) VALUES ('I have formed a quality committee to');
INSERT INTO prefixes (segment) VALUES ('I need a status report on how you');
INSERT INTO prefixes (segment) VALUES ('I was a music major in college, but I am an effective manager because I');
INSERT INTO prefixes (segment) VALUES ('I will be gone three hours for lunch.  While I am away, I want you to');
INSERT INTO prefixes (segment) VALUES ('If it doesn''t help the bottom line, it''s not worth doing.  But you should always');
INSERT INTO prefixes (segment) VALUES ('If you want to walk the walk and talk the talk, you have to');
INSERT INTO prefixes (segment) VALUES ('In order to evangelize synergy, our paradigm requires that we');
INSERT INTO prefixes (segment) VALUES ('In order to play in this space, we have to');
INSERT INTO prefixes (segment) VALUES ('In order to take the elevator beyond the top floor, you need to');
INSERT INTO prefixes (segment) VALUES ('In our industry sector, the score is love-fifteen, so we must');
INSERT INTO prefixes (segment) VALUES ('In the new millennium, it is crucial that we');
INSERT INTO prefixes (segment) VALUES ('In today''s business model, we must');
INSERT INTO prefixes (segment) VALUES ('Instead of wasting time questioning the competence of upper management, you should');
INSERT INTO prefixes (segment) VALUES ('It is important that we');
INSERT INTO prefixes (segment) VALUES ('It is not too late to');
INSERT INTO prefixes (segment) VALUES ('It''s attitude, not altitude, that is important.  Therefore, you must');
INSERT INTO prefixes (segment) VALUES ('Lead, follow, or');
INSERT INTO prefixes (segment) VALUES ('Let''s drill down to the core and');
INSERT INTO prefixes (segment) VALUES ('Let''s raise the bar and');
INSERT INTO prefixes (segment) VALUES ('Let''s run the flag up the flagpole and see if we can');
INSERT INTO prefixes (segment) VALUES ('Leverage the technology delta and');
INSERT INTO prefixes (segment) VALUES ('Logically, we must');
INSERT INTO prefixes (segment) VALUES ('Managers are often misunderstood.  But they always');
INSERT INTO prefixes (segment) VALUES ('Many of you will');
INSERT INTO prefixes (segment) VALUES ('Morale is low.  Therefore, you must');
INSERT INTO prefixes (segment) VALUES ('My degree in liberal arts qualifies me to be an executive.  Thus, I');
INSERT INTO prefixes (segment) VALUES ('New rule: Effective immediately, you shall');
INSERT INTO prefixes (segment) VALUES ('No executives were laid off in the recent''rightsizing''because they');
INSERT INTO prefixes (segment) VALUES ('Now is a good time to');
INSERT INTO prefixes (segment) VALUES ('Now is the time for us to');
INSERT INTO prefixes (segment) VALUES ('Now that we are up to speed, you may want to');
INSERT INTO prefixes (segment) VALUES ('One of your most significant objectives is to');
INSERT INTO prefixes (segment) VALUES ('Our CEO paid a consultant $50,000 for the following advice:');
INSERT INTO prefixes (segment) VALUES ('Our consultant tells me that we should');
INSERT INTO prefixes (segment) VALUES ('Our customers will expect us to');
INSERT INTO prefixes (segment) VALUES ('Our evangelistic strategic synergization requires that we');
INSERT INTO prefixes (segment) VALUES ('Our executives are NOT overpaid.  They are the only ones who');
INSERT INTO prefixes (segment) VALUES ('Our executives know how to');
INSERT INTO prefixes (segment) VALUES ('Our formula for success requires a new paradigm of synergy, and we must');
INSERT INTO prefixes (segment) VALUES ('Our goal is to');
INSERT INTO prefixes (segment) VALUES ('Our objective is clear.  We must');
INSERT INTO prefixes (segment) VALUES ('Our objective is to dynamically');
INSERT INTO prefixes (segment) VALUES ('Our solution is that we always');
INSERT INTO prefixes (segment) VALUES ('Our strategy requires a zero-deviation precision focus, and we must');
INSERT INTO prefixes (segment) VALUES ('Our success will be defined by how we');
INSERT INTO prefixes (segment) VALUES ('Our success will be measured by how we');
INSERT INTO prefixes (segment) VALUES ('Our synergy is defined by how we');
INSERT INTO prefixes (segment) VALUES ('Our Vice President of Synergy empowers you to');
INSERT INTO prefixes (segment) VALUES ('Our visionaries have hired consultants to them that we should');
INSERT INTO prefixes (segment) VALUES ('Our VPs are concerned because you do not');
INSERT INTO prefixes (segment) VALUES ('Please transcribe my voice messages to text.  Then,');
INSERT INTO prefixes (segment) VALUES ('Position yourself for success.  Simply');
INSERT INTO prefixes (segment) VALUES ('Program yourself for success, and');
INSERT INTO prefixes (segment) VALUES ('Put yourself in your boss''s shoes.  They you can');
INSERT INTO prefixes (segment) VALUES ('Quality thinking will lead you to');
INSERT INTO prefixes (segment) VALUES ('Quality, not quantity.  Also, let''s see you');
INSERT INTO prefixes (segment) VALUES ('Religiously,');
INSERT INTO prefixes (segment) VALUES ('Revenue schmevenue!  It''s the stock price that matters.  That''s why we');
INSERT INTO prefixes (segment) VALUES ('Rome wasn''t built in a day. Now,');
INSERT INTO prefixes (segment) VALUES ('Sales are down this quarter because no one took me seriously when I told you to');
INSERT INTO prefixes (segment) VALUES ('Seamlessly, you manager will');
INSERT INTO prefixes (segment) VALUES ('Since nothing is more certain than change, we must');
INSERT INTO prefixes (segment) VALUES ('Some associates have remarked that I speak meaningless buzz-phrases.  Actually, I');
INSERT INTO prefixes (segment) VALUES ('Some of you will');
INSERT INTO prefixes (segment) VALUES ('Some say the glass is half full; some say it is half empty.  You must');
INSERT INTO prefixes (segment) VALUES ('Stop what you are doing and give me a status report on how you');
INSERT INTO prefixes (segment) VALUES ('Success and failure are opposites.  That is why we need to');
INSERT INTO prefixes (segment) VALUES ('Success is not a crap-shoot if we');
INSERT INTO prefixes (segment) VALUES ('Synergy leads to shared success, so we must');
INSERT INTO prefixes (segment) VALUES ('Take a leadership role and');
INSERT INTO prefixes (segment) VALUES ('Take responsibility and');
INSERT INTO prefixes (segment) VALUES ('Take the customer''s temperature and then you can');
INSERT INTO prefixes (segment) VALUES ('Team effort is required, so you need to');
INSERT INTO prefixes (segment) VALUES ('The 411 on our new strategy is that we will');
INSERT INTO prefixes (segment) VALUES ('The bar has been raised.  Let''s see you');
INSERT INTO prefixes (segment) VALUES ('The board of directors would like you to');
INSERT INTO prefixes (segment) VALUES ('The bottom line is that we need to');
INSERT INTO prefixes (segment) VALUES ('The goal posts have been moved.  All associates now should');
INSERT INTO prefixes (segment) VALUES ('The marketing department would like you to');
INSERT INTO prefixes (segment) VALUES ('The person I promote to management will have the ability to');
INSERT INTO prefixes (segment) VALUES ('The quality team will');
INSERT INTO prefixes (segment) VALUES ('There is a good reason why no executives lost their jobs in the last downsizing.  They');
INSERT INTO prefixes (segment) VALUES ('Think! ... And you shall');
INSERT INTO prefixes (segment) VALUES ('To achieve value multiplicity, we must endeavor to');
INSERT INTO prefixes (segment) VALUES ('To avoid decruitment,');
INSERT INTO prefixes (segment) VALUES ('To boost morale, all associates will');
INSERT INTO prefixes (segment) VALUES ('To effectively fulcrum our team synergy, we should');
INSERT INTO prefixes (segment) VALUES ('To effectively solution a paradigm, you need to');
INSERT INTO prefixes (segment) VALUES ('To get traction in this space, we will');
INSERT INTO prefixes (segment) VALUES ('To improve communications with management, please');
INSERT INTO prefixes (segment) VALUES ('To keep ahead of the competition, we must');
INSERT INTO prefixes (segment) VALUES ('To rebuild customer confidence, we must');
INSERT INTO prefixes (segment) VALUES ('Together we have to');
INSERT INTO prefixes (segment) VALUES ('Together, we will');
INSERT INTO prefixes (segment) VALUES ('Unilaterally, we should');
INSERT INTO prefixes (segment) VALUES ('Until morale improves, you will');
INSERT INTO prefixes (segment) VALUES ('We are at DEFCON 1, so you must');
INSERT INTO prefixes (segment) VALUES ('We are going to push the envelope and');
INSERT INTO prefixes (segment) VALUES ('We can''t fulcrum the paradigm unless you');
INSERT INTO prefixes (segment) VALUES ('We must seize the moment and');
INSERT INTO prefixes (segment) VALUES ('We shall boldly move ahead and');
INSERT INTO prefixes (segment) VALUES ('We will be the first on the block to');
INSERT INTO prefixes (segment) VALUES ('We will circle the wagons and');
INSERT INTO prefixes (segment) VALUES ('We will endeavor to');
INSERT INTO prefixes (segment) VALUES ('We will strive to');
INSERT INTO prefixes (segment) VALUES ('We''ll put the''dot''in''dot-com''when we');
INSERT INTO prefixes (segment) VALUES ('We''re leaving money on the table unless we');
INSERT INTO prefixes (segment) VALUES ('What can you do for your company?  For starters, you can');
INSERT INTO prefixes (segment) VALUES ('While leveraging synergy across multimedia paradigms, we need to');
INSERT INTO prefixes (segment) VALUES ('While you waste time serving our customers, our executive staff will');
INSERT INTO prefixes (segment) VALUES ('Work smarter, not harder!  And to start, you can');
INSERT INTO prefixes (segment) VALUES ('You are a mere tactical plebe.  Only a VP such as myself can');
INSERT INTO prefixes (segment) VALUES ('You are being assigned to a revenue mentor so you can');
INSERT INTO prefixes (segment) VALUES ('You can show your appreciation for your manager.  One way is to');
INSERT INTO prefixes (segment) VALUES ('You could be an executive too, if only you would');
INSERT INTO prefixes (segment) VALUES ('You have a bad attitude.  Now, start contributing and');
INSERT INTO prefixes (segment) VALUES ('You will never be a manager unless you');
INSERT INTO prefixes (segment) VALUES ('Your managers are NOT oxygen wasters.  After all, they');
INSERT INTO prefixes (segment) VALUES ('Your manager''s manager will be impressed if you');
INSERT INTO prefixes (segment) VALUES ('Your performance review will include observations on how well you');


INSERT INTO verbs (segment) VALUES ('abridge');
INSERT INTO verbs (segment) VALUES ('abstract');
INSERT INTO verbs (segment) VALUES ('accelerate');
INSERT INTO verbs (segment) VALUES ('accent');
INSERT INTO verbs (segment) VALUES ('accept');
INSERT INTO verbs (segment) VALUES ('acquire');
INSERT INTO verbs (segment) VALUES ('act on');
INSERT INTO verbs (segment) VALUES ('action');
INSERT INTO verbs (segment) VALUES ('adjust');
INSERT INTO verbs (segment) VALUES ('administer');
INSERT INTO verbs (segment) VALUES ('advance');
INSERT INTO verbs (segment) VALUES ('aggregate');
INSERT INTO verbs (segment) VALUES ('alliance');
INSERT INTO verbs (segment) VALUES ('allure');
INSERT INTO verbs (segment) VALUES ('amass');
INSERT INTO verbs (segment) VALUES ('anticipate');
INSERT INTO verbs (segment) VALUES ('architect');
INSERT INTO verbs (segment) VALUES ('assimilate');
INSERT INTO verbs (segment) VALUES ('assure');
INSERT INTO verbs (segment) VALUES ('attain');
INSERT INTO verbs (segment) VALUES ('attract');
INSERT INTO verbs (segment) VALUES ('attune');
INSERT INTO verbs (segment) VALUES ('augment');
INSERT INTO verbs (segment) VALUES ('augmentize');
INSERT INTO verbs (segment) VALUES ('author');
INSERT INTO verbs (segment) VALUES ('back-burner');
INSERT INTO verbs (segment) VALUES ('basis');
INSERT INTO verbs (segment) VALUES ('benchmark');
INSERT INTO verbs (segment) VALUES ('blend');
INSERT INTO verbs (segment) VALUES ('blueprint');
INSERT INTO verbs (segment) VALUES ('bolster');
INSERT INTO verbs (segment) VALUES ('bottom-line');
INSERT INTO verbs (segment) VALUES ('brand');
INSERT INTO verbs (segment) VALUES ('break loose');
INSERT INTO verbs (segment) VALUES ('breed');
INSERT INTO verbs (segment) VALUES ('bridge');
INSERT INTO verbs (segment) VALUES ('broker');
INSERT INTO verbs (segment) VALUES ('build bridges across');
INSERT INTO verbs (segment) VALUES ('build');
INSERT INTO verbs (segment) VALUES ('burn a focus spot into');
INSERT INTO verbs (segment) VALUES ('buy into');
INSERT INTO verbs (segment) VALUES ('capitalize on');
INSERT INTO verbs (segment) VALUES ('carve');
INSERT INTO verbs (segment) VALUES ('centralize');
INSERT INTO verbs (segment) VALUES ('charge');
INSERT INTO verbs (segment) VALUES ('chart');
INSERT INTO verbs (segment) VALUES ('checkpoint');
INSERT INTO verbs (segment) VALUES ('circumscribe');
INSERT INTO verbs (segment) VALUES ('circumvent');
INSERT INTO verbs (segment) VALUES ('cite');
INSERT INTO verbs (segment) VALUES ('click and stick');
INSERT INTO verbs (segment) VALUES ('close in on');
INSERT INTO verbs (segment) VALUES ('close');
INSERT INTO verbs (segment) VALUES ('coalesce');
INSERT INTO verbs (segment) VALUES ('collect');
INSERT INTO verbs (segment) VALUES ('combine');
INSERT INTO verbs (segment) VALUES ('combine');
INSERT INTO verbs (segment) VALUES ('command');
INSERT INTO verbs (segment) VALUES ('commit');
INSERT INTO verbs (segment) VALUES ('compile');
INSERT INTO verbs (segment) VALUES ('compound');
INSERT INTO verbs (segment) VALUES ('concur with');
INSERT INTO verbs (segment) VALUES ('condense');
INSERT INTO verbs (segment) VALUES ('configure');
INSERT INTO verbs (segment) VALUES ('conjure');
INSERT INTO verbs (segment) VALUES ('consider');
INSERT INTO verbs (segment) VALUES ('consolidate');
INSERT INTO verbs (segment) VALUES ('constitute');
INSERT INTO verbs (segment) VALUES ('consummate');
INSERT INTO verbs (segment) VALUES ('converge');
INSERT INTO verbs (segment) VALUES ('convoke');
INSERT INTO verbs (segment) VALUES ('cull');
INSERT INTO verbs (segment) VALUES ('cultivate');
INSERT INTO verbs (segment) VALUES ('cut and paste');
INSERT INTO verbs (segment) VALUES ('debit');
INSERT INTO verbs (segment) VALUES ('defend');
INSERT INTO verbs (segment) VALUES ('deliver');
INSERT INTO verbs (segment) VALUES ('delve into');
INSERT INTO verbs (segment) VALUES ('demand');
INSERT INTO verbs (segment) VALUES ('deploy');
INSERT INTO verbs (segment) VALUES ('derive');
INSERT INTO verbs (segment) VALUES ('design');
INSERT INTO verbs (segment) VALUES ('designate');
INSERT INTO verbs (segment) VALUES ('detail');
INSERT INTO verbs (segment) VALUES ('develop');
INSERT INTO verbs (segment) VALUES ('devise');
INSERT INTO verbs (segment) VALUES ('diagram');
INSERT INTO verbs (segment) VALUES ('dictate');
INSERT INTO verbs (segment) VALUES ('digitize');
INSERT INTO verbs (segment) VALUES ('dilate');
INSERT INTO verbs (segment) VALUES ('dimensionalize');
INSERT INTO verbs (segment) VALUES ('direct');
INSERT INTO verbs (segment) VALUES ('discover');
INSERT INTO verbs (segment) VALUES ('distance ourselves from');
INSERT INTO verbs (segment) VALUES ('diversify');
INSERT INTO verbs (segment) VALUES ('document');
INSERT INTO verbs (segment) VALUES ('dominate');
INSERT INTO verbs (segment) VALUES ('downsize');
INSERT INTO verbs (segment) VALUES ('dress-rehearse');
INSERT INTO verbs (segment) VALUES ('drill down to');
INSERT INTO verbs (segment) VALUES ('drive');
INSERT INTO verbs (segment) VALUES ('e-complish');
INSERT INTO verbs (segment) VALUES ('e-cumulate');
INSERT INTO verbs (segment) VALUES ('e-deliver');
INSERT INTO verbs (segment) VALUES ('edify');
INSERT INTO verbs (segment) VALUES ('e-discuss');
INSERT INTO verbs (segment) VALUES ('effect');
INSERT INTO verbs (segment) VALUES ('embellish');
INSERT INTO verbs (segment) VALUES ('embody');
INSERT INTO verbs (segment) VALUES ('embrace');
INSERT INTO verbs (segment) VALUES ('emerge');
INSERT INTO verbs (segment) VALUES ('emphasize');
INSERT INTO verbs (segment) VALUES ('empower');
INSERT INTO verbs (segment) VALUES ('enable');
INSERT INTO verbs (segment) VALUES ('e-nable');
INSERT INTO verbs (segment) VALUES ('engage');
INSERT INTO verbs (segment) VALUES ('engineer');
INSERT INTO verbs (segment) VALUES ('enhance');
INSERT INTO verbs (segment) VALUES ('enjoin');
INSERT INTO verbs (segment) VALUES ('enlighten');
INSERT INTO verbs (segment) VALUES ('ennoble');
INSERT INTO verbs (segment) VALUES ('ensure');
INSERT INTO verbs (segment) VALUES ('envision');
INSERT INTO verbs (segment) VALUES ('epitomize');
INSERT INTO verbs (segment) VALUES ('establish');
INSERT INTO verbs (segment) VALUES ('evangelize');
INSERT INTO verbs (segment) VALUES ('evoke');
INSERT INTO verbs (segment) VALUES ('e-volutionize');
INSERT INTO verbs (segment) VALUES ('evolve');
INSERT INTO verbs (segment) VALUES ('execute');
INSERT INTO verbs (segment) VALUES ('exercise');
INSERT INTO verbs (segment) VALUES ('expedite');
INSERT INTO verbs (segment) VALUES ('exploit');
INSERT INTO verbs (segment) VALUES ('explore');
INSERT INTO verbs (segment) VALUES ('exponentialize');
INSERT INTO verbs (segment) VALUES ('extend');
INSERT INTO verbs (segment) VALUES ('extol');
INSERT INTO verbs (segment) VALUES ('facilitate');
INSERT INTO verbs (segment) VALUES ('factor');
INSERT INTO verbs (segment) VALUES ('fathom');
INSERT INTO verbs (segment) VALUES ('fine-tune');
INSERT INTO verbs (segment) VALUES ('focus on');
INSERT INTO verbs (segment) VALUES ('forestall');
INSERT INTO verbs (segment) VALUES ('forge');
INSERT INTO verbs (segment) VALUES ('fortify');
INSERT INTO verbs (segment) VALUES ('forward engineer');
INSERT INTO verbs (segment) VALUES ('foster');
INSERT INTO verbs (segment) VALUES ('found');
INSERT INTO verbs (segment) VALUES ('fractionate');
INSERT INTO verbs (segment) VALUES ('frontline');
INSERT INTO verbs (segment) VALUES ('fulcrum');
INSERT INTO verbs (segment) VALUES ('further');
INSERT INTO verbs (segment) VALUES ('fuse');
INSERT INTO verbs (segment) VALUES ('fusion');
INSERT INTO verbs (segment) VALUES ('fusionize');
INSERT INTO verbs (segment) VALUES ('future-proof');
INSERT INTO verbs (segment) VALUES ('gamify');
INSERT INTO verbs (segment) VALUES ('generate');
INSERT INTO verbs (segment) VALUES ('generate');
INSERT INTO verbs (segment) VALUES ('get the mean deviation of');
INSERT INTO verbs (segment) VALUES ('get');
INSERT INTO verbs (segment) VALUES ('give birth to');
INSERT INTO verbs (segment) VALUES ('give life to');
INSERT INTO verbs (segment) VALUES ('graph');
INSERT INTO verbs (segment) VALUES ('grow');
INSERT INTO verbs (segment) VALUES ('guide');
INSERT INTO verbs (segment) VALUES ('hand off');
INSERT INTO verbs (segment) VALUES ('harbor');
INSERT INTO verbs (segment) VALUES ('harbor');
INSERT INTO verbs (segment) VALUES ('harmonize');
INSERT INTO verbs (segment) VALUES ('harness');
INSERT INTO verbs (segment) VALUES ('harvest');
INSERT INTO verbs (segment) VALUES ('hasten');
INSERT INTO verbs (segment) VALUES ('have a hand in');
INSERT INTO verbs (segment) VALUES ('hone');
INSERT INTO verbs (segment) VALUES ('horizontalize');
INSERT INTO verbs (segment) VALUES ('host');
INSERT INTO verbs (segment) VALUES ('ignite');
INSERT INTO verbs (segment) VALUES ('illuminate');
INSERT INTO verbs (segment) VALUES ('implement');
INSERT INTO verbs (segment) VALUES ('incentivize');
INSERT INTO verbs (segment) VALUES ('incorporate');
INSERT INTO verbs (segment) VALUES ('incubate');
INSERT INTO verbs (segment) VALUES ('induce');
INSERT INTO verbs (segment) VALUES ('influence');
INSERT INTO verbs (segment) VALUES ('inherit');
INSERT INTO verbs (segment) VALUES ('initiate');
INSERT INTO verbs (segment) VALUES ('innovate');
INSERT INTO verbs (segment) VALUES ('innovent');
INSERT INTO verbs (segment) VALUES ('integrate');
INSERT INTO verbs (segment) VALUES ('intensify');
INSERT INTO verbs (segment) VALUES ('interpolate');
INSERT INTO verbs (segment) VALUES ('introduce');
INSERT INTO verbs (segment) VALUES ('intuitivize');
INSERT INTO verbs (segment) VALUES ('invent');
INSERT INTO verbs (segment) VALUES ('invest ourselves in');
INSERT INTO verbs (segment) VALUES ('invoke');
INSERT INTO verbs (segment) VALUES ('kick off');
INSERT INTO verbs (segment) VALUES ('lead the industry with');
INSERT INTO verbs (segment) VALUES ('leap into');
INSERT INTO verbs (segment) VALUES ('leverage');
INSERT INTO verbs (segment) VALUES ('litmus test');
INSERT INTO verbs (segment) VALUES ('machinate');
INSERT INTO verbs (segment) VALUES ('mainstream');
INSERT INTO verbs (segment) VALUES ('make a religion of');
INSERT INTO verbs (segment) VALUES ('map the course for');
INSERT INTO verbs (segment) VALUES ('map');
INSERT INTO verbs (segment) VALUES ('market-test');
INSERT INTO verbs (segment) VALUES ('marshal');
INSERT INTO verbs (segment) VALUES ('mastermind');
INSERT INTO verbs (segment) VALUES ('materialize');
INSERT INTO verbs (segment) VALUES ('maximize');
INSERT INTO verbs (segment) VALUES ('merge');
INSERT INTO verbs (segment) VALUES ('merge');
INSERT INTO verbs (segment) VALUES ('mesh');
INSERT INTO verbs (segment) VALUES ('midwife');
INSERT INTO verbs (segment) VALUES ('migrate');
INSERT INTO verbs (segment) VALUES ('move on to');
INSERT INTO verbs (segment) VALUES ('mull over');
INSERT INTO verbs (segment) VALUES ('muster');
INSERT INTO verbs (segment) VALUES ('nail down');
INSERT INTO verbs (segment) VALUES ('navigate');
INSERT INTO verbs (segment) VALUES ('net out');
INSERT INTO verbs (segment) VALUES ('network');
INSERT INTO verbs (segment) VALUES ('noodle');
INSERT INTO verbs (segment) VALUES ('observe');
INSERT INTO verbs (segment) VALUES ('offload');
INSERT INTO verbs (segment) VALUES ('offshoot');
INSERT INTO verbs (segment) VALUES ('open');
INSERT INTO verbs (segment) VALUES ('open-think');
INSERT INTO verbs (segment) VALUES ('opportunity');
INSERT INTO verbs (segment) VALUES ('optimize');
INSERT INTO verbs (segment) VALUES ('orchestrate');
INSERT INTO verbs (segment) VALUES ('organize');
INSERT INTO verbs (segment) VALUES ('overcome inertia on');
INSERT INTO verbs (segment) VALUES ('over-deploy');
INSERT INTO verbs (segment) VALUES ('over-engineer');
INSERT INTO verbs (segment) VALUES ('over-think');
INSERT INTO verbs (segment) VALUES ('overwhelm');
INSERT INTO verbs (segment) VALUES ('parse');
INSERT INTO verbs (segment) VALUES ('partnership');
INSERT INTO verbs (segment) VALUES ('pave the road to');
INSERT INTO verbs (segment) VALUES ('pencil in');
INSERT INTO verbs (segment) VALUES ('perceive');
INSERT INTO verbs (segment) VALUES ('perfect');
INSERT INTO verbs (segment) VALUES ('ping');
INSERT INTO verbs (segment) VALUES ('pinpoint');
INSERT INTO verbs (segment) VALUES ('pipeline');
INSERT INTO verbs (segment) VALUES ('plan');
INSERT INTO verbs (segment) VALUES ('plot');
INSERT INTO verbs (segment) VALUES ('polarize');
INSERT INTO verbs (segment) VALUES ('polish');
INSERT INTO verbs (segment) VALUES ('ponder');
INSERT INTO verbs (segment) VALUES ('populate');
INSERT INTO verbs (segment) VALUES ('prepare a report on');
INSERT INTO verbs (segment) VALUES ('prepare');
INSERT INTO verbs (segment) VALUES ('promote');
INSERT INTO verbs (segment) VALUES ('propose');
INSERT INTO verbs (segment) VALUES ('provide');
INSERT INTO verbs (segment) VALUES ('provision');
INSERT INTO verbs (segment) VALUES ('pursue');
INSERT INTO verbs (segment) VALUES ('purvey');
INSERT INTO verbs (segment) VALUES ('push the envelope on');
INSERT INTO verbs (segment) VALUES ('put a price on');
INSERT INTO verbs (segment) VALUES ('quarterback');
INSERT INTO verbs (segment) VALUES ('ramp up');
INSERT INTO verbs (segment) VALUES ('reach for');
INSERT INTO verbs (segment) VALUES ('ready');
INSERT INTO verbs (segment) VALUES ('realign');
INSERT INTO verbs (segment) VALUES ('realize');
INSERT INTO verbs (segment) VALUES ('realize');
INSERT INTO verbs (segment) VALUES ('reap');
INSERT INTO verbs (segment) VALUES ('recognize');
INSERT INTO verbs (segment) VALUES ('re-content');
INSERT INTO verbs (segment) VALUES ('re-deploy');
INSERT INTO verbs (segment) VALUES ('refine');
INSERT INTO verbs (segment) VALUES ('regulate');
INSERT INTO verbs (segment) VALUES ('reinvent');
INSERT INTO verbs (segment) VALUES ('relate to');
INSERT INTO verbs (segment) VALUES ('remedy');
INSERT INTO verbs (segment) VALUES ('render');
INSERT INTO verbs (segment) VALUES ('renew our commitment to');
INSERT INTO verbs (segment) VALUES ('rescue');
INSERT INTO verbs (segment) VALUES ('research');
INSERT INTO verbs (segment) VALUES ('respect');
INSERT INTO verbs (segment) VALUES ('revamp');
INSERT INTO verbs (segment) VALUES ('revenuize');
INSERT INTO verbs (segment) VALUES ('revisit');
INSERT INTO verbs (segment) VALUES ('revolutionize');
INSERT INTO verbs (segment) VALUES ('rightsize');
INSERT INTO verbs (segment) VALUES ('rock');
INSERT INTO verbs (segment) VALUES ('rotate');
INSERT INTO verbs (segment) VALUES ('rule');
INSERT INTO verbs (segment) VALUES ('ruminate');
INSERT INTO verbs (segment) VALUES ('safeguard');
INSERT INTO verbs (segment) VALUES ('salute');
INSERT INTO verbs (segment) VALUES ('scale');
INSERT INTO verbs (segment) VALUES ('schedule');
INSERT INTO verbs (segment) VALUES ('screen');
INSERT INTO verbs (segment) VALUES ('scrutinize');
INSERT INTO verbs (segment) VALUES ('sectorize');
INSERT INTO verbs (segment) VALUES ('seduce');
INSERT INTO verbs (segment) VALUES ('seize');
INSERT INTO verbs (segment) VALUES ('seize');
INSERT INTO verbs (segment) VALUES ('self-direct');
INSERT INTO verbs (segment) VALUES ('service');
INSERT INTO verbs (segment) VALUES ('set standards for');
INSERT INTO verbs (segment) VALUES ('shape');
INSERT INTO verbs (segment) VALUES ('shepard');
INSERT INTO verbs (segment) VALUES ('sideline');
INSERT INTO verbs (segment) VALUES ('sign off on');
INSERT INTO verbs (segment) VALUES ('smoke out');
INSERT INTO verbs (segment) VALUES ('snapshot');
INSERT INTO verbs (segment) VALUES ('solidify');
INSERT INTO verbs (segment) VALUES ('solution');
INSERT INTO verbs (segment) VALUES ('solutionize');
INSERT INTO verbs (segment) VALUES ('sow');
INSERT INTO verbs (segment) VALUES ('spreadsheet');
INSERT INTO verbs (segment) VALUES ('springboard');
INSERT INTO verbs (segment) VALUES ('story-tell');
INSERT INTO verbs (segment) VALUES ('strategize');
INSERT INTO verbs (segment) VALUES ('streamline');
INSERT INTO verbs (segment) VALUES ('strengthen');
INSERT INTO verbs (segment) VALUES ('stress');
INSERT INTO verbs (segment) VALUES ('strip-mine');
INSERT INTO verbs (segment) VALUES ('structure');
INSERT INTO verbs (segment) VALUES ('summarize');
INSERT INTO verbs (segment) VALUES ('superinduce');
INSERT INTO verbs (segment) VALUES ('supplement');
INSERT INTO verbs (segment) VALUES ('surgically target');
INSERT INTO verbs (segment) VALUES ('sustain');
INSERT INTO verbs (segment) VALUES ('synchronize');
INSERT INTO verbs (segment) VALUES ('syndicate');
INSERT INTO verbs (segment) VALUES ('synergize');
INSERT INTO verbs (segment) VALUES ('synopsize');
INSERT INTO verbs (segment) VALUES ('take ownership on');
INSERT INTO verbs (segment) VALUES ('target');
INSERT INTO verbs (segment) VALUES ('thumbnail');
INSERT INTO verbs (segment) VALUES ('thunk');
INSERT INTO verbs (segment) VALUES ('transcend');
INSERT INTO verbs (segment) VALUES ('trailblaze');
INSERT INTO verbs (segment) VALUES ('transform');
INSERT INTO verbs (segment) VALUES ('transition');
INSERT INTO verbs (segment) VALUES ('transpose');
INSERT INTO verbs (segment) VALUES ('trim');
INSERT INTO verbs (segment) VALUES ('tune');
INSERT INTO verbs (segment) VALUES ('turn the page on');
INSERT INTO verbs (segment) VALUES ('unify');
INSERT INTO verbs (segment) VALUES ('unite');
INSERT INTO verbs (segment) VALUES ('unleash');
INSERT INTO verbs (segment) VALUES ('upgrade');
INSERT INTO verbs (segment) VALUES ('upspeak');
INSERT INTO verbs (segment) VALUES ('upthink');
INSERT INTO verbs (segment) VALUES ('usher in');
INSERT INTO verbs (segment) VALUES ('utilize');
INSERT INTO verbs (segment) VALUES ('value');
INSERT INTO verbs (segment) VALUES ('virtualize');
INSERT INTO verbs (segment) VALUES ('visualize');
INSERT INTO verbs (segment) VALUES ('voice');
INSERT INTO verbs (segment) VALUES ('weave');
INSERT INTO verbs (segment) VALUES ('weigh');
INSERT INTO verbs (segment) VALUES ('weight');
INSERT INTO verbs (segment) VALUES ('welcome');
INSERT INTO verbs (segment) VALUES ('welcome');
INSERT INTO verbs (segment) VALUES ('whiteboard');
INSERT INTO verbs (segment) VALUES ('write the book on');
INSERT INTO verbs (segment) VALUES ('wrought');
INSERT INTO verbs (segment) VALUES ('action-forward');

-- For Development of new Categories
INSERT INTO adjectives (segment,category) VALUES ('closed-door','law');
INSERT INTO adjectives (segment,category) VALUES ('co-branded','law');
INSERT INTO adjectives (segment,category) VALUES ('collateral','law');
INSERT INTO adjectives (segment,category) VALUES ('collective','law');
INSERT INTO adjectives (segment,category) VALUES ('committed','law');
INSERT INTO adjectives (segment,category) VALUES ('compiled','law');
INSERT INTO adjectives (segment,category) VALUES ('confidential','law');
INSERT INTO adjectives (segment,category) VALUES ('cool','law');

INSERT INTO connectors (segment,category) VALUES ('strategic','law');
INSERT INTO connectors (segment,category) VALUES ('tactical','law');
INSERT INTO connectors (segment,category) VALUES ('the','law');
INSERT INTO connectors (segment,category) VALUES ('the best','law');
INSERT INTO connectors (segment,category) VALUES ('our firm''s','law');
INSERT INTO connectors (segment,category) VALUES ('the competition''s','law');
INSERT INTO connectors (segment,category) VALUES ('the client''s','law');
INSERT INTO connectors (segment,category) VALUES ('the matrix of','law');
INSERT INTO connectors (segment,category) VALUES ('the most','law');
INSERT INTO connectors (segment,category) VALUES ('the cost of','law');
INSERT INTO connectors (segment,category) VALUES ('tomorrow''s','law');
INSERT INTO connectors (segment,category) VALUES ('unplugged','law');
INSERT INTO connectors (segment,category) VALUES ('virtual','law');
INSERT INTO connectors (segment,category) VALUES ('visible','law');
INSERT INTO connectors (segment,category) VALUES ('warehouses full of','law');
INSERT INTO connectors (segment,category) VALUES ('your','law');

INSERT INTO nouns (segment,category) VALUES ('characteristics','law');
INSERT INTO nouns (segment,category) VALUES ('circles of influence','law');
INSERT INTO nouns (segment,category) VALUES ('client expectations','law');
INSERT INTO nouns (segment,category) VALUES ('client criticalities','law');
INSERT INTO nouns (segment,category) VALUES ('client engagements','law');
INSERT INTO nouns (segment,category) VALUES ('client preferences','law');
INSERT INTO nouns (segment,category) VALUES ('client sensibilities','law');
INSERT INTO nouns (segment,category) VALUES ('billable hours','law');

INSERT INTO prefixes (segment,category) VALUES ('According to THE PARTY OF THE FIRST PART','law');
INSERT INTO prefixes (segment,category) VALUES ('Wherein','law');
INSERT INTO prefixes (segment,category) VALUES ('Whereas','law');
INSERT INTO prefixes (segment,category) VALUES ('Hitherto known','law');

INSERT INTO verbs (segment,category) VALUES ('demand','law');
INSERT INTO verbs (segment,category) VALUES ('attach','law');
INSERT INTO verbs (segment,category) VALUES ('subpena','law');
INSERT INTO verbs (segment,category) VALUES ('create','law');
INSERT INTO verbs (segment,category) VALUES ('consruct','law');
